added new commands

diff --git a/gsx-dev/new b/gsx-dev/new
--- a/gsx-dev/new
+++ b/gsx-dev/new
@@ -2,24 +2,49 @@
 
 source variables
 
-if [ $# == 1 ]; then
-        mkdir $1
-        echo "Successfully created the folder at the current path $1"
-  else
-      if [ $# == 2 ]; then
-            cd $1
-            mkdir $2
-            cd "${INSTALLDIR}"
-            echo "$INSTALLDIR"
-            echo "Successfully created the folder $2 at path $1"
-            
-        else
-            
-            echo "+------------------------------------------------------------------------------------+"
-            echo "|Syntax error: This command only accepts 1 or 2 arguments, $# arguments were provided|"
-            echo "|Correct Syntax: 'new <Directory> <Folder name>                                      |"
-            echo "+------------------------------------------------------------------------------------+"
-            afplay ./storage/assets/error.mov
-            exit 1
+
+
+
+if [ $1 == "dir" ]; then
+        if [ $# == 2 ]; then
+            mkdir $3
+            echo "Successfully created the folder at the current path $2"
+          else
+           if [ $# == 3 ]; then
+               cd $2
+               mkdir $3
+               cd "${INSTALLDIR}"
+               echo "$INSTALLDIR"
+               echo "Successfully created the folder $3 at path $2"   
+             else
+              echo "+------------------------------------------------------------------------------------+"
+              echo "|Syntax error:This command only accepts 2 or 3 arguments, $# arguments were provided  |"
+              echo "|Correct Syntax: 'new (dir|file) <Directory> <File or dir name>                      |"
+              echo "+------------------------------------------------------------------------------------+"
+              afplay ./storage/assets/error.mov
+              exit 1
+           fi
         fi
-  fi
+  else
+    if [ $1 == "file" ]; then
+        if [ $# == 2 ]; then
+            touch $2
+            echo "Successfully created the file $2 at the current path $2"
+          else
+           if [ $# == 3 ]; then
+               cd $2
+               >$3
+               cd "${INSTALLDIR}"
+               echo "$INSTALLDIR"
+               echo "Successfully created the file $3 at path $2"   
+             else
+              echo "+------------------------------------------------------------------------------------+"
+              echo "|Syntax error: This command only accepts 2 or 3 arguments, $# arguments were provided  |"
+              echo "|Correct Syntax: 'new (dir|file) <Directory> <File or dir name>                       |"
+              echo "+------------------------------------------------------------------------------------+"
+              afplay ./storage/assets/error.mov
+              exit 1
+           fi
+        fi    
+    fi
+fi
